### ISSUE TITLE
Port samples from the old repo

### ISSUE THREAD

**Issue by Roger-luo** [Roger-luo/MAGMA.jl#1]
@JerryChen97 could you port the samples in your fork to this repo? 

The steps are:

1. fork this repo
2. copy your sample to this repo
3. open a PR (so I could comment)
3. include some tests that shows your sample is working

Currently, we just need to make the sample work on our own machine with manually installed MAGMA, and let's consider friendlier setup procedure later in the summer.

I think neither JuliaGPU nor me own the original repo, so we couldn't have issues or comments on that repo. I'll be able to comment here, and make changes, we will transfer this repo to JuliaGPU later.

**Comment by JerryChen97** [comment]
okay thanks for notification!

**Comment by Roger-luo** [comment]
I think this is done now. closed.
