### ISSUE TITLE
make use of multiple dispatch

### ISSUE THREAD

**Issue by Roger-luo** [Roger-luo/MAGMA.jl#24]
https://github.com/Roger-luo/MAGMA.jl/blob/e195ba72feadb51af712a2b823d7cc08d2609b06/src/dense/linearsystemsolver.jl#L13

**Comment by JerryChen97** [comment]
Under certain circumstances, such as gebrd, I indeed applied both a loop for element types and a loop for interfaces {CuMatrix, Matrix} to automatically generate all the wrappers.
However, there are some other situations when it comes to some subroutines like gesvd and gesdd, that its arguments consist of two different lists for Real and Complex: the Complex one has an additional argument called "rwork" while the Real one doesn't. Hence, I splited the whole loops into two, correspondingly treating the Complex and the Real situations.

**Comment by Roger-luo** [comment]
I think this is resolved now.
